### PR TITLE
Add community documentation

### PR DESCRIPTION
**Pull request by RichardLitt**
Dearest humans,

You are missing some important community files. I am adding them here for you!

Here are some things you should do manually before merging this Pull Request:

- [ ] Check the email in the Code of Conduct. We've added in "haad@headbanggames.com".
- [ ] Update the Contributing guide to include any repository-specific requests, or to point to a global Contributing document.
- [ ] Check that the license name and year is correct. I've added the MIT license, which should suit most purposes.
- [ ] Check the licensee in the License. We've licensed this to "[INSERT LICENSEE]".
- [ ] Update your README. It is only specced out, and will need more work. I suggest [standard-readme](https://github.com/RichardLitt/standard-readme) for this.
- [ ] Check the package.json, and make sure that nothing drastic happened. 
- [ ] Consider adding Travis. Travis is useful not only for tests, but also for [greenkeeper](https://greenkeeper.io/) and [semantic-release](https://github.com/semantic-release/semantic-release).

Note: This pull request was automatically generated by https://github.com/mntnr/build-a-space. Found an issue? [Let me know!](https://github.com/mntnr/build-a-space/issues)

### CODE REVIEW

**Comment by RichardLitt** [comment]
I've edited, rebased, and updated this. It is ready for a review.

**Comment by adam-palazzo** [comment]
We don't need the dates in the license file, do we? You removed them in the README but updated them in the LICENSE, I would be consistent and remove both of them, unless there is a reason to have the dates.

**Comment by adam-palazzo** [comment]
There also isn't a README up on npm: https://www.npmjs.com/package/orbit-crypto

**Comment by RichardLitt** [comment]
The dates should be fine - the README doesn't really need them if they're not important, and I figured why not add it to the License. Could dump that change. 

The npm README should update when the version is bumped.

**Pull request merged**
